name: Setup iOS Simulator
description: Create, boot, and export an iOS Simulator for Maestro.

inputs:
  runtime-name:
    description: iOS runtime name.
    required: true
  device-type-name:
    description: iOS Simulator device type name.
    required: true
  simulator-name:
    description: Simulator device name prefix.
    required: false
    default: MaestroPlayground

runs:
  using: composite
  steps:
    - name: Boot simulator
      shell: bash
      env:
        RUNTIME_NAME: ${{ inputs.runtime-name }}
        DEVICE_TYPE_NAME: ${{ inputs.device-type-name }}
        SIMULATOR_NAME: ${{ inputs.simulator-name }}
      run: |
        "$GITHUB_ACTION_PATH/../../../utils/setup/ios-simulator.sh"
